### ISSUE TITLE
Connections not closed with SpringTransactionManager

### ISSUE THREAD

**Issue by GrannyOlli** [gruelbox/transaction-outbox#134]
Hi,

thanks for your great library!

I tried it out using the spring-integration. I noticed that db-connections won't be given back to the connection pool if a callback throws an exception. This leads to the situation, that after some failed callbacks no connections are available any more.

The problem seems to be that the default methods of com.gruelbox.transactionoutbox.TransactionManager are not wrapped by Springs TransactionInterceptor, because they are not directly annotated with @Transactional.

Example: Method inTransactionThrows called in TransactionOutboxImpl.updateAttemptCount is not wrapped by Springs transaction-aspect and thus connections are not given back to the connection pool after the method ends. inTransactionThrows calls inTransactionReturnsThrows, which is not intercepted by the aop-proxy when called from within the object, only when called directly.

Copying all default methods to SpringTransactionManager and annotating them with @Transactional solves the problem in my test setup.

Example:

@Beta
@Service
public class SpringTransactionManager implements ThreadLocalContextTransactionManager {
        ...
	@Override
	@Transactional(propagation = Propagation.REQUIRES_NEW)
	public void inTransaction(Runnable runnable) {
		uncheck(() -> inTransactionReturnsThrows(ThrowingTransactionalSupplier.fromRunnable(runnable)));
	}

	@Override
	@Transactional(propagation = Propagation.REQUIRES_NEW)
	public void inTransaction(TransactionalWork work) {
		uncheck(() -> inTransactionReturnsThrows(ThrowingTransactionalSupplier.fromWork(work)));
	}
....

Best regards
Oliver

**Comment by badgerwithagun** [comment]
Thanks @GrannyOlli ! Would you consider opening a pull request with this change?

We don't use Spring here on a daily basis so are quite grateful for feedback.

**Comment by kzkvv** [comment]
I got this problem too. HikariPool is filled completely when calling transactionOutbox.flush() in a loop (total=15, active=15) and then I get the error "hikaripool-1-connection unavailable". Increasing the pool will not be a good solution and will only help for a short time. 
I tried GrannyOlli's solution and it worked for me, now the pool doesn't stay full.

**Comment by amseager** [comment]
+1, looks like a blocker for using it in Spring-based apps. Made a PR with the solution presented by @GrannyOlli and @kzkvv
