### ISSUE TITLE
Problems with jakarta 3 dependencies

### ISSUE THREAD

**Issue by amseager** [gruelbox/transaction-outbox#165]
Jakarta 3 brings us a new package structure replacing `javax.*` with `jakarta.*`. 
As I understand it, in transaction-outbox project, this migration had happened while hibernate validator was updated from 6 to 7. So now, we have a lot of `jakarta.*` imports across the project. This causes a lot of troubles because a vast majority of libraries and frameworks (e.g. the newest spring boot) still use jakarta 2 with `javax.*` imports, so you need to use an older version of transaction-outbox in this case to make the code compile.
Is it possible to do something with it? We can downgrade hibernate validator or keep two versions of transaction-outbox? Or even refactor classes with potential problems to make them independent from it.

**Comment by badgerwithagun** [comment]
We've been hit with this at Goji too and are frozen on an earlier version.

It's actually looking like a mistake to have taken this hibernate-validator update into the project. I am tempted to revert the related commits in master and jump up a major version of transaction-outbox.

Happy to take a PR , but if not I'll probably do this in the next few weeks.

**Comment by badgerwithagun** [comment]
In the meantime, the 2.x branch is active for fixes and we are publishing new versions of 2.x. just not bumping dependences.
