### ISSUE TITLE
Different problems while migrating to Java 16/17 because of --illegal-access=deny by default

### ISSUE THREAD

**Issue by amseager** [gruelbox/transaction-outbox#185]
Because of https://openjdk.java.net/jeps/403 several problems appear while using java 16/17:

- CGLIB has been destroyed completely, so now it isn't possible to use inheritance proxies. Looks like this library isn't in an active development state (the latest version of it was released in 2019) despite the cglib develovers know about these problems https://github.com/cglib/cglib/issues/191
It's still possible to use interface-based proxies though.

- there is a problem with serializing/deserializing classes from `java.time` with the `DefaultInvocationSerializer` (based on gson). Same reason - this module is not open.

- I can't actually build this project on openjdk 17 - something with the deprecated `com.sun.` packages (haven't dig into it tbh).

That's what I found atm. If I find sth else, I'll post it here too.

**Comment by badgerwithagun** [comment]
Hmm, the writing was on the wall for CGLIB.

I expect these are about to become higher priority for us as we're moving to Java 17 shortly.

**Comment by stustill** [comment]
I've raised PR #202 to replace CGLIB with ByteBuddy.

**Comment by badgerwithagun** [comment]
Re

> there is a problem with serializing/deserializing classes from java.time with the DefaultInvocationSerializer (based on gson). Same reason - this module is not open.

My response on #217 might be of interest.  We've actually found `DefaultInvocationSerializer` too restrictive for us and have written our own.  Happy to open-source it.

**Comment by amseager** [comment]
@badgerwithagun Great idea! But I think in this case it'd be required to change some other classes like `Invocation` as well. Have you managed to do it already?

**Comment by badgerwithagun** [comment]
Oh yes@ amseager.

It works with the existing SPI, no problem. It's been in production for nearly a year. It wasn't trivial to write and does produce some slightly odd JSON in order to get all the type information in, but it works.

**Comment by tsg21** [comment]
The OP probably knows this, but it may be useful to others to note that you can avoid this warning/issue by exclusively using interface proxies rather than inheritance proxies. This wasn't immediately obvious to me.

i.e. if you have some code that looks like:
```
transactionOutbox.schedule(Something.class).doSomething(args);
```
Then so long as you make sure that `Something.class` is an interface (not a class) then the warning goes away.

**Comment by amseager** [comment]
@tsg21 ye, it's stated in the first paragraph (which is about cglib)

I've actually been using interface proxies in my project for the last few months and can confirm that they work well.
The only drawback is that you need to extract that `doSomething` method to the interface (i.e. make it public) while it could be package-private with cglib.

Haven't tested the recent approach with bytebuddy yet, need to give it a try.

**Comment by badgerwithagun** [comment]
Yep, I'm going to close this now.  Concrete class proxies are now only supported if ByteBuddy (plus possibly also Objenesis) are on the classpath, and if they're not, only interface proxies are supported.  It now builds and works fine up to Java 17.
