### ISSUE TITLE
Migrate flag is not used

### ISSUE THREAD

**Issue by luisalves00** [gruelbox/transaction-outbox#194]
Hi,

On the config documentation you have: 
```
// Disable automatic creation and migration of the outbox table, forcing the application to manage
        // migrations itself
        .migrate(false)
```

But the flag doesn't seem to do anything. I've looked at the code and here:

```java
  @Override
  public void initialize() {
    if (initialized.compareAndSet(false, true)) {
      try {
        persistor.migrate(transactionManager);
      } catch (Exception e) {
        initialized.set(false);
        throw e;
      }
    }
  }
```

and here:

```java
  @Override
  public void migrate(TransactionManager transactionManager) {
    DefaultMigrationManager.migrate(transactionManager, dialect);
  }
```

Probably you are missing the IF condition to check if we want to do the migration or not, or am I missing something?

**Comment by deanrecord** [comment]
This should be fixed by https://github.com/gruelbox/transaction-outbox/commit/ffc284a50b568ceb8811a92f98ec31a251bee3b0

**Comment by badgerwithagun** [comment]
I don't think there has been a maven central release since then, but you should be fine to use the GitHub snapshots channel.

**Comment by luisalves00** [comment]
Any reason to not release to maven central?

**Comment by badgerwithagun** [comment]
Nope! I'll do it now :)

**Comment by badgerwithagun** [comment]
Done! Could take a day to propagate.

**Comment by luisalves00** [comment]
Was fast :) thanks a lot.
