### ISSUE TITLE
DefaultInvocationSerializer does not allow java.util.UUID

### ISSUE THREAD

**Issue by tsg21** [gruelbox/transaction-outbox#217]
`java.util.UUID` is a commonly-used JDK class and is commonly used to model surrogate identifiers. It is therefore a good candidate to be passed as an argument to "scheduled" invocations with transaction outbox.

`DefaultInvocationSerializer` does not currently appear to allow it. There are various work-arounds, but it seems like something that should be allowed.  Do you agree? If so I will raise a PR.

**Comment by amseager** [comment]
@tsg21 you mean to add support for UUID by default?

 Currently, it should work if you add `UUID.class` as a serializable type as described [here](https://github.com/gruelbox/transaction-outbox#configuration-reference):

```
DefaultInvocationSerializer.builder()
    .serializableTypes(Set.of(UUID.class))
    .build()
```

**Comment by tsg21** [comment]
Yes, I am arguing it should be allowed by default. It's a standard-enough type that I think should be included.

**Comment by badgerwithagun** [comment]
Sure, go ahead!  Feel free to raise a PR.

For what it's worth, we actually don't use `DefaultInvocationSerializer` here. We built a version that uses Jackson and just blindly serializes and unserializes. It's not as secure, but being able to use complex object trees as arguments without worrying about serialization is worth the tradeoff in time and general pain.

The implementation wasn't as trivial as it sounds. I could probably pop it on here as an optional extra if anyone thought it'd be useful.
