### ISSUE TITLE
Is transaction-outbox stable with postgreSql driver version 14.5.0 ?

### ISSUE THREAD

**Issue by karlnicholas** [gruelbox/transaction-outbox#323]
We have been upgrading to  postgreSql driver version 14.5.0 and maven will link in our specific version instead of the transaction-outbox dependency version. 

There is a PR from the dependency-bot to update to 14.5.0 but the tests are failing. Are these tests flaky or is there is actually an issue with transaction-outbox combination and postgreSql driver version 14.5.0?

**Comment by badgerwithagun** [comment]
Hmmm. That test is intended to highlight potential issues with locking behaviour on the DB and will only fail intermittently. If it's flaking, that's a bad sign. It's going to need a bit of investigation.

**Comment by badgerwithagun** [comment]
Looks like the latest version of the postgres driver (https://github.com/gruelbox/transaction-outbox/pull/318) is running green. I'll kick it a few more times just to make sure. It does look like a locking issue was fixed in the driver (!)

**Comment by badgerwithagun** [comment]
Yep, seems stable. Merged the latest driver into the tests.
