### ISSUE TITLE
transactionoutbox-spring depends on hibernate-core

### ISSUE THREAD

**Issue by tsg21** [gruelbox/transaction-outbox#34]
I am using Spring, but not Hibernate, and the code in SpringTransactionManager won't work for me. There is no `SessionFactory` from which to fetch the active `Connection`.

I _think_ the answer is just to inject the DataSource, and use connections from that. You should be able to require that this DataSource has been either
a) wrapped in [TransactionAwareDataSourceProxy](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/datasource/TransactionAwareDataSourceProxy.html) in a non-JTA context
b) is a JTA connection that will handle the transactionality for you.

If this make sense, I might be able to create a PR.

**Comment by badgerwithagun** [comment]
Please do! I'm not using Spring myself. I just created it to prove to myself that the SPI worked (there's a note to that effect [in the readme](https://github.com/gruelbox/transaction-outbox/tree/master/transactionoutbox-spring). It would be great to do the (probably pretty minimal) work to get this up to scratch.

**Comment by tsg21** [comment]
I'm not 100% sure whether you should inject `DataSource` and wrap it in `TransactionAwareDataSourceProxy` yourself, or just require that it has been by the provider.

**Comment by tsg21** [comment]
Is a bit out of date, but I think this provides the "correct" answer:
https://docs.spring.io/spring/docs/4.2.x/spring-framework-reference/html/transaction.html#tx-resource-synchronization-low

`DataSourceUtils.getConnection(dataSource)`

**Comment by badgerwithagun** [comment]
Sounds promising.

FWIW, I am keen that in the longer term this isn't tied to JDBC either (since Spring is where it's all happening atm in terms of moving non-blocking I/O forward), but I'll roll that into #40 as I work on it. For now we're tied to JDBC so the fix for this can assume that as a baseline.
