### ISSUE TITLE
Release 5.2.337 not present on Maven Central

### ISSUE THREAD

**Issue by skastenholz** [gruelbox/transaction-outbox#408]
Problem:

I am wondering how and when release 5.2.337 will be available on Maven Central (https://mvnrepository.com/artifact/com.gruelbox/transactionoutbox-core) since https://github.com/gruelbox/transaction-outbox/actions/runs/4383418970 failed.

Expectation:

Release 5.2.337 is available on Maven Central.

**Comment by badgerwithagun** [comment]
Right. The `gpg` key has expired. I'll generate a new one.

**Comment by badgerwithagun** [comment]
Deployed.
