### ISSUE TITLE
Invocation args are serialized as Json Object instead of array

### ISSUE THREAD

**Issue by RomainWilbert** [gruelbox/transaction-outbox#449]
See [https://github.com/gruelbox/transaction-outbox/blob/master/transactionoutbox-jackson/src/main/java/com/gruelbox/transactionoutbox/jackson/CustomInvocationSerializer.java](https://github.com/gruelbox/transaction-outbox/blob/master/transactionoutbox-jackson/src/main/java/com/gruelbox/transactionoutbox/jackson/CustomInvocationSerializer.java)

They should be serialized like parameterTypes are ?

**Comment by badgerwithagun** [comment]
Hey @RomainWilbert. Huh, good spot. I've not checked; does it actually produce different JSON?

**Comment by RomainWilbert** [comment]
Hi @badgerwithagun. I can't remember exactly the use case. Maybe i wanted to deserialize the args and i had to trick a little.

**Comment by badgerwithagun** [comment]
What's the impact?

Just wondering whether it's worth a fix if it's harmless.

**Comment by RomainWilbert** [comment]
I think my use case is : I wanted to deserialize the args and display entries in a table which allowed to replay failed invocations

**Comment by badgerwithagun** [comment]
It's possible it's deliberate. I can't remember for certain but I think there might be some type sensitivity this covers for. Certainly the use of an array would be the obvious option, but the guy that implemented the Jackson serialiser had a hell of a time making it work for polymorphic calls.
