### ISSUE TITLE
Java Module system compatibility

### ISSUE THREAD

**Issue by driesdeproost** [gruelbox/transaction-outbox#505]
Hi

Thanks for this project. We think it looks promising and would like to try it out in one of our projects.
However, we use the Java module system and we are not able to require `transactionoutbox-core` and `transactionoutbox-spring` at the same time.  

![screenshot](https://github.com/gruelbox/transaction-outbox/assets/14177727/17b0b534-3efe-46ea-b028-9130c8ebf685)

All subproject artifacts contain modules that export to the same package `com.gruelbox.transactionoutbox`.
I suppose this is default behaviour when the same package structure is used throughout the project. 

Split packages are not allowed by the Java module system.
Would it be possible to alter the package structure in every subproject so that they are more specific?

**Comment by badgerwithagun** [comment]
Hi @driesdeproost.  I would like to make this change but it'd be a big compatibility break.

I started doing it as part of #40 and have never quite got it to a point where it's ready to be released. Every now and then I make another big push to get it finished - maybe one for the holiday season!

**Comment by badgerwithagun** [comment]
@driesdeproost it will take a few versions before I can remove the duplicated/deprecated classes by merging #533, but when I do, this should be fixed

**Comment by driesdeproost** [comment]
Awesome, thanks a lot!

We worked around it for now by just copying some implementation into our project and that worked perfectly so far!
Looking forward to being able to remove that duplicated code some day :)
