### ISSUE TITLE
Integration Problems with Spring Boot Application - looking for more code samples

### ISSUE THREAD

**Issue by sgoeschl** [gruelbox/transaction-outbox#531]
Hi folks,

I am a bit hesitant to create a report but I'm stuck with Spring's Boot configuration magic (version 3.1.6) - well, sort of expected :)

Are there any hints, more code samples, mailing lists or whatsoever?! I'm really not eager to write my own outbox code because it is hard when aiming at production quality.

With the Spring integration library I got the outbox working but my Spring Boot test are failing since Flyway decided to ignore my Postgres test container

```
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: Connection to localhost:5435 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:5435 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

When using the core library alone the Spring Boot test are working but the the library is unable to find the current transaction (using transaction manager and Hikari DS) - guess that stems from byte code magic and calling the wrong proxy.

**Comment by sgoeschl** [comment]
Could be that my Flyway problem stems from a faulty @ComponentScan annotation :-)

```
@ComponentScan({"com.gruelbox.transactionoutbox", "my.company.com})
```

I will keep you informed :)

**Comment by badgerwithagun** [comment]
Please do!

I'm intending on improving the Spring support a bit over the next few days - the main improvement being to add `@Scheduled` support for the [background worker](https://github.com/gruelbox/transaction-outbox#set-up-the-background-worker). I'll probably also give virtual thread support a whirl and improve the instructions.

I'm not certain what you're seeing is an issue with this library, but if it is it could be Flyway and this library's upgrade code conflicting with each other. You could always disable migration and copy the migrations to your Flyway setup:

```
TransactionOutbox.builder()
    .transactionManager(transactionManager)
    .persistor(DefaultPersistor.builder()
        .dialect(Dialect.POSTGRESQL_9)
        .migrate(false)
        .build())
   ...
```

**Comment by badgerwithagun** [comment]
@sgoeschl I've updated the example/test code. Does this help? https://github.com/gruelbox/transaction-outbox/tree/better-spring-example/transactionoutbox-spring/src/test

**Comment by badgerwithagun** [comment]
Example code now merged and `README` updated.
