### ISSUE TITLE
Possibility of not processing the OutboxEntry immediatly

### ISSUE THREAD

**Issue by jsolferreira** [gruelbox/transaction-outbox#751]
Is it possible to not publish the OutboxEntry after the transaction ends and only publish it when calling flush()?

Same behavior we get when using .ordered("...")

**Comment by badgerwithagun** [comment]
Interesting. What is the use-case?

**Comment by jsolferreira** [comment]
Trying to achieve something like this: https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/transactional-outbox.html

Instead of publishing right after the transaction ends, we would like just store the entries in the database table and have an external service request their republication.

**Comment by badgerwithagun** [comment]
I think this may be missing the point of the library somewhat.  The relational DB pattern on the AWS page isn't great or particularly scaleable. If you want to do it that way, you don't need this library, you only need a table in your application.

The way I would use transaction-outbox is more directly similar to the SQS approach:

![image](https://github.com/user-attachments/assets/80ac02c1-5e80-4db7-a0f9-0f9b8a1c092c)

```
App code -> outbox job (with unique request id) -> send to SQS (or make a REST call)
----------> receive from SQS (or make a rest call) -> outbox job (with unique request id) -> App code
```

In this model you are using outbox as a resilient, self-deduplicating transport, avoiding the need for your second application to access you first application's DB.

**Comment by jsolferreira** [comment]
Understood!
